### ISSUE TITLE
queuecomplete Event not firing 4.3.0

### ISSUE THREAD

**Issue by mbarmettler** [dropzone/dropzone-bower#1]
Hi enyo,

we have used verison 4.3.0 in our project.
due to a reported issue, that the "queuecomplete" seems not to fire correctrly while using multi file upload, i try to upgrade to a newer version of the dropzone.
therefore i tried to uninstal the "normal" dropzone and replace it with "dropzon-bower".

what i tried:
- uninsttall dropzone 4.3.0
- bower install dropzone-bower
ouput:
bower dropzone-bower#*          cached https://github.com/dropzone/dropzone-bower.git#5.9.3
bower dropzone-bower#*        validate 5.9.3 against https://github.com/dropzone/dropzone-bower.git#*
bower dropzone-bower#5.9.0   ENOTFOUND Package dropzone-bower not found

i dont understand why its not possible to install?

in my bower.json

    "dropzone-bower": "5.9.3",

i hope you understand what i mean with this.

thanks for any hint

**Comment by enyo** [comment]
Please use version 6.x.x if possible.
